### PR TITLE
[PWDK-2478] Setup CKEditor

### PR DESCRIPTION
**Pull request by katherinedavenia**
### What type of PR is this? (_check all applicable_)

- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [x] Setup
- [ ] Code Refactor
- [ ] Performance Improvements
- [ ] Test
- [ ] Build
- [ ] CI
- [ ] Revert

### Screenshots (_optional_)
Screenshot 2023-07-18 at 18 34 34

### CODE REVIEW

**Review by shadiqfauzi — APPROVED** [review]
oke semoga aman pas deploy wkwk

**Review by kuntiarso — DISMISSED** [review]

**Comment by kuntiarso** [comment]
> oke semoga aman pas deploy wkwk

deployment scriptnya mesti diupdate sepertinya

**Comment by katherinedavenia** [comment]
> > oke semoga aman pas deploy wkwk
> 
> deployment scriptnya mesti diupdate sepertinya

ini gmnn mas

**Review by kuntiarso — APPROVED** [review]
kat ini nanti boleh di merge aja ya buat sekalian liat bakal error atau engganya

**Review by hiljaker — APPROVED** [review]

**Pull request merged**
